# Generated by Django 6.0.1 on 2026-01-10 16:29

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('templates_app', '0003_alter_order_schema_snapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='InviteInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('schema', models.JSONField()),
                ('public_slug', models.SlugField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invite', to='templates_app.order')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='templates_app.template')),
            ],
        ),
    ]
