# Generated by Django 6.0.1 on 2026-01-12 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='inviteinstance',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
