# Generated by Django 6.0.1 on 2026-01-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0002_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='schema_snapshot',
            field=models.JSONField(editable=False),
        ),
    ]
