# Generated by Django 6.0.1 on 2026-01-12 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0004_order_amount_order_updated_at_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='template_component',
            field=models.CharField(default='RoyalWeddingTemplate', help_text='React component name for this template design', max_length=100),
        ),
    ]
