# Generated by Django 6.0.1 on 2026-01-15 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0005_template_template_component'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='default_hero_image',
            field=models.ImageField(blank=True, help_text='Default template preview image shown to buyers', null=True, upload_to='templates/'),
        ),
    ]
