# Generated by Django 6.0.1 on 2026-01-15 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0006_template_default_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='default_image',
            field=models.ImageField(blank=True, help_text='Category card image shown to buyers', null=True, upload_to='categories/'),
        ),
    ]
