# Generated by Django 6.0.1 on 2026-01-16 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates_app', '0007_category_default_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='template',
            name='is_preview',
            field=models.BooleanField(default=False, help_text='Show in homepage preview (max 5 templates recommended)'),
        ),
    ]
